<?php
/**
 * Created by PhpStorm.
 * User: Krasen
 * Date: 16/6/21
 * Time: 12:06
 * Email: jhasheng@hotmail.com
 */

namespace Purple\Collectors;


use Illuminate\Foundation\Application;
use Symfony\Component\HttpFoundation\Response;

class View extends AbstractCollection
{
    protected $name = 'view';

    protected $icon = 'eye-slash';

    protected $template = 'views';

    public function before(Application $application)
    {
        parent::before($application); // TODO: Change the autogenerated stub

        /**
         * @var $event \Illuminate\Events\Dispatcher
         */
        $event = $application['events'];
        $that = $this;
        $event->listen('composing:*', function($view) use($that) {
            $time = microtime(true);

//            $views->addEvent(
//                'view ' . $view->getName(),
//                'Rendering a view',
//                $time,
//                $time,
//                array(
//                    'name' => $view->getName(),
//                    'data' => $that->replaceUnserializable($view->getData())
//                )
//            );
        });
    }


    public function after(Application $app, Response $response)
    {
        $this->calcBadge();
    }
}